# Generated by Django 6.0.4 on 2026-05-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
